// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udlpqkmobzgugckmastb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkbHBxa21vYnpndWdja21hc3RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4Njc0NjUsImV4cCI6MjA2NjQ0MzQ2NX0.bIyGtbCRzm_z5_SH_TwWTh5pxxYjuzkFCpuXrvolc8w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);